version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"

  myapp:
    image: openjdk:17-jdk-slim
    container_name: myapp-container
    depends_on:
      - mysql
    volumes:
      - ./app.jar:/app/app.jar
    working_dir: /app
    command: sh -c "sleep 20 && java -jar app.jar"
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass